---
services:
  app:
    build: .
    image: paste:latest
    container_name: paste
    ports:
      - "3000:3000"
    environment:
      - REDIS_ADDR=redis:6379
      - ADDRESS=0.0.0.0
      - PORT=3000
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"

volumes:
  redis-data:
    name: redis-data
